### ISSUE TITLE
The PDF file shows #### for global character

### ISSUE THREAD

**Issue by AbnerSui** [danfickle/openhtmltopdf#174]
Hi,
I had a try on openhtmltopdf sandbox, but it shows # for global character.
![image](https://user-images.githubusercontent.com/18004574/35953004-da146986-0c3f-11e8-944f-d69a358aefcd.png)

**Comment by danfickle** [comment]
Hi @AbnerSui 

The sandbox doesn’t include cjk fonts so you’ll have to set up a project on your computer. #129 outlines how to use CJK fonts.

**Comment by vipcxj** [comment]
The solution in tutorial works very well. Perhaps this works as well:
```java
 GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
 ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("A.ttf")));
```
I haven't test yet.

**Comment by AbnerSui** [comment]
@danfickle thanks for the reply. I have 2 questions.
1. The global characters, 中文字符, has no relations with any fonts, why should I use CJK font, why not other fonts?
2. If there are multiple fonts used in HTML, I need to add all the fonts to the PdfRendererBuilder?

**Comment by AbnerSui** [comment]
Hi @danfickle , sorry to disturb you. But I have multiple languages need to support, only CJK font seems not enough. Can I ask when you plan to support global characters ? In fact, I can accept to lose the font style, but can't accept # showing there. Thank you so much for building such a great library.

**Comment by rototor** [comment]
@AbnerSui If you need all different languages you just need to declare the font family according and register all needed fonts. E.g.

```css
*  {
font-family:Arial, "Malgun Gothic", MingLiU, "MS Gothic", "Microsoft JhengHei", "Noto Sans", Hevletica, Sans-serif, serif';
}
```

And of course you muster register all this different font files in the builder. If you register the files with all styles then you also get the different styles. This are the names of the windows font files for this fonts: 
```java
	static final String[] malgun = new String[] { "malgun.ttf", "malgunbd.ttf", };
	static final String[] mingliu = new String[] { "mingliu.ttc" };
	static final String[] msgothic = new String[] { "msgothic.ttc" };
	static final String[] msj = new String[] { "msjh.ttf", "msjhbd.ttf" };
       // Only on Win10+, not Win 7
	static final String[] msj_ttc = new String[] { "msjh.ttc", "msjhbd.ttc" };
```
You must locate (in %WINDIR%/fonts or where every) all this fonts and register them in the builder. 

Note: The sandbox is outdated, don't test this with the sandbox. 

Having different glyphs and fonts is working fine for me.

**Comment by AbnerSui** [comment]
Hi @rototor , thank you for reply.
I met one wierd thing, HTML like below
```
<html>
<head>
<title></title>
<style type="text/css">html{font-family:sans-serif,simfang;}</style>
</head>
<body>
<span style="font-family:sans-serif;font-weight:bold;">中文字符</span><br />
<span style="font-family:simfang;font-weight:bold;">中文字符</span><br />
中文字符<br />
<body>
</html>
```

My java code is like below
```
PdfRendererBuilder builder = new PdfRendererBuilder();
builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
builder.defaultTextDirection(PdfRendererBuilder.TextDirection.LTR);
builder.useFont(() -> {
                    try {
                        return new FileInputStream("simfang.ttf");
                    } catch (FileNotFoundException e) {
                        mLog.error("simfang not found");
                        return null;
                    }
                }, "simfang", 400, PdfRendererBuilder.FontStyle.NORMAL, true);
builder.useFont(() -> {
                    try {
                        return new FileInputStream("sans-serif.ttf");
                    } catch (FileNotFoundException e) {
                        mLog.error("sans-serif not found");
                        return null;
                    }
                }, "sans-serif", 400, PdfRendererBuilder.FontStyle.NORMAL, true);
OutputStream os = new FileOutputStream("test.pdf");
org.w3c.dom.Document doc = html5ParseDocument(htmlString, htmlFileInputStream);
builder.withW3cDocument(doc, htmlFileInputStream);
builder.toStream(os);
builder.run();
```
But the PDF result is wierd, like below

**####**
中文字符
中文字符

The first line became ####, but the style is still there, font-weight:bold;
The second shows correctly, but lose style, font-weight:bold;
The third line shows correctly.

**Comment by rototor** [comment]
Thats to be expected. Only the fonts you specify in font-family are used, in the order you specify them.

sans-serif is the builtin default font. It has font styles and all that stuff. But is does not have the glyphs for the Chinese characters, usually it only has a subset of all possible characters. 

The font-family logic works the following: For each character it is tried to look up a glyph. If a font does not exists, then that font family is skipped (i.e. thats the way font-family is used mostly on the web). But also if that font does not have a glyph for the given character the font is skip. When a font is skipped the next font in the font-family is tried, till a matching character is found. If no font provides a glyph, then OpenHtmlToPDF falls back to print ```#```, so that you see that there is a something missing. 

The second and the third line should be the same, shouldn't they? Can you provide a screenshot of how this looks? (you can paste screenshots directly into the comment field of githup)

You did not provide a version of simfang for FontStyle.BOLD, so of course the font wont display "bold". You need a font file for each font variation you want. E.g. in the JDK 9 font folder there are different versions of the LucidaBright font:

```
LucidaBrightRegular.ttf
LucidaBrightItalic.ttf 
LucidaBrightDemiItalic.ttf
LucidaBrightDemiBold.ttf 
````
If you would like to use them you would need to register them all and specify the correct weight and style while registering. It does not matter if you register the file using the API or using the standard CSS font registration rule (see e.g. https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp).

In Java2D (Graphics2D etc.) it is possible to let the Java synthesize different font variations. Any typographer would call them dead ugly (in opposite to correctly hand crafted bold or italic fonts), but the API provides the possibility to draw the font with styles the font does not really provide. It then just gets streched (in case of bold) or skewed (in case of italics).

PDF on the other side does not provide this possibility. If you don't have a font with a given style, then it wont show up as e.g. bold. You can always use the builtin PDF fonts (e.g. Helvetica) which provides all font variations. But when using custom fonts you need to provide all font variations.

**Comment by AbnerSui** [comment]
@rototor thanks very much. Your reply helps to understand the library behavior better.
Thank you again for offering me so much help and building such a great library.
Finally, if someday the library can support all languages without showing #, it would be awesome.
Looking forward to it.

**Comment by AbnerSui** [comment]
Reopen for other users, the comments may help them.

**Comment by AbnerSui** [comment]
We found one font from Windows operation system, arialuni.ttf, arial unicode ms, which can be used on almost all languages in the world. Hope this work around can help other users.

**Comment by rkhlin** [comment]
Hi there,

I was using the Flying Saucer library before and it all went ok until I upgrade my Spring framework to v5 so that I have to look for a newer library to generate PDF with Chinese in it.

I had read quite a few posts and tried many ways, but still seeing ###. Not sure what is going on.
Please help.

My css file:
@CHARSET "UTF-8";
@font-face {
    font-family: "Arial Unicode MS";
    src: url('arialuni.ttf');
}
* {
  font-family: "Arial Unicode MS",sans-serif;
}

HTML file:
<!DOCTYPE html>
<html>
<head>
	<title>Testing</title>

</head>
<link rel="stylesheet" type="text/css" href="test.css" media="all" />
<body>
	<h1>每星期三<br/>
		Every Wednesday</h1>
</body>
</html>

Java:
	public static void main(String[] args) throws Exception {
        try (OutputStream os = new FileOutputStream("E:/Temp/out.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
//            builder.useFont(new File("E:/Temp/arialuni.ttf"),"Arial Unicode MS");
            builder.useFastMode();
            builder.withUri("file:///E:/Temp/index.html");
            builder.toStream(os);
            builder.run();
        }
    }

Result:

![out](https://user-images.githubusercontent.com/619188/132008032-64953643-e99b-4e1a-8d84-aadfbbe26912.jpg)
