### ISSUE TITLE
can't convert http resources to pdf by http client

### ISSUE THREAD

**Issue by zhouzach** [danfickle/openhtmltopdf#221]
I wander where transfer url to code:

public class OkHttpStreamFactory implements HttpStreamFactory {
    private final OkHttpClient client = new OkHttpClient();

    public HttpStream getUrl(String url) {
        Request request = new Request.Builder()
                .url("https://www.baidu.com")
                .build();

        try {
            final Response response = client.newCall(request).execute();

            return new HttpStream() {
                public InputStream getStream() {
                    return response.body().byteStream();
                }

                public Reader getReader() {
                    return response.body().charStream();
                }
            };
        }
        catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }
}

public class SimpleUsage {
    public static void main(String[] args)
    {
        new SimpleUsage().exportToPdfBox("https://www.baidu.com", "/Users/zach/output.pdf");
    }

    public void exportToPdfBox(String url, String out)
    {
        OutputStream os = null;

        try {
            os = new FileOutputStream(out);

            try {
                PdfRendererBuilder builder = new PdfRendererBuilder();

                OkHttpStreamFactory http = new OkHttpStreamFactory();
                builder.useHttpStreamImplementation(http);
                builder.toStream(os);
                builder.run();

            } catch (Exception e) {
                e.printStackTrace();
             
            } finally {
                try {
                    os.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        catch (IOException e1) {
            e1.printStackTrace();
        }
    }
}

After many tries, I got the error:

java.lang.NullPointerException
	at com.openhtmltopdf.bidi.ParagraphSplitter.splitRoot(ParagraphSplitter.java:168)
	at com.openhtmltopdf.layout.BoxBuilder.splitParagraphs(BoxBuilder.java:93)
	at com.openhtmltopdf.layout.BoxBuilder.createRootBox(BoxBuilder.java:99)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.layout(PdfBoxRenderer.java:306)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:36)
	at SimpleUsage.exportToPdfBox(SimpleUsage.java:30)
	at SimpleUsage.main(SimpleUsage.java:10)

What's wrong with it?
Thanks a lot for your help

**Comment by rototor** [comment]
You seem to trigger a unrelated bug. What version of OpenHTMLToPDF are you using? 

Also note: Trying to render a random webpage using this library will result in a broken looking output. This library is not able to render any modern HTML5, as it misses many features (e.g. no flexbox, no javascript at all, ...). But this is also not what this library is for. You can create great looking PDF reports with correct page breaks and repeating table headers using this library - but you must special craft the HTML and CSS for this. Please take a look at the examples and [testcases](https://github.com/danfickle/openhtmltopdf/tree/open-dev-v1/openhtmltopdf-examples/src/main/resources/testcases).

You also must register all the special fonts you need. E.g. you need  a Chinese font to have any Chinese characters appear in the output. Otherwise you will only see '#' in the PDF.

If all you want is to render any current web page as a PDF you should consider https://wkhtmltopdf.org/ - it will use WebKit and supports all new shiny features. But don't expect to be happy with the page breaks, and don't even think about table headers repeated on each page - there is no such feature as ```-fs-table-paginate: paginate``` in normal CSS.

**Comment by zhouzach** [comment]
@rototor Firstly, thanks very much for reply.I still two question:
1. At the part of PLUGGABLE HTTP CLIENT from
https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/docs/integration-guide.md
the bottom: builder.useHttpStreamImplementation(new OkHttpStreamFactory()), the http client request what url, I can't find where to call its getUrl method

2.Actually, I try to use wkhtmltopdf and don't know to add token because I request url needed to authentication

**Comment by danfickle** [comment]
I think we can close this. As @rototor said, this project is not a headless web browser. Please reopen if required.
