### ISSUE TITLE
White page added with @page named

### ISSUE THREAD

**Issue by Zefling** [danfickle/openhtmltopdf#233]
In this case, a blank page is added before the first styled page:

```html
<html>
<head>
<style>
/* The following fonts are installed on the server: */
.handwriting {
  font-family: 'handwriting', serif;
}
.arabic {
  font-family: 'arabic', serif;
}
.deja {
  /* Contains glyphs for many languages. */
  font-family: 'deja-sans', sans-serif;
}
/*
Also you can use the PDF built-in fonts: 
 - sans-serif
 - serif
 - monospace
*/

@page test {
  size: A4;
  margin: 3.5cm 1.5cm 2.5cm 1.5cm;
}
.pagetest{ 
  page : test 
}

</style>
</head>
<body>
<div class="pagetest">
<div class="handwriting" style="text-align:center;font-size: 90px;color:orange;">
Hello World!
</div>
</div>
</body>
</html>
```
I tested several cases, the first page is necessarily `@page` unnamed.For generated content (for example, with mustache) where the first page would be present or not, it really complicated the implementation.

**Comment by danfickle** [comment]
Hi @Zefling,

I hope this is better late than never. After looking at the code, it turns out there is logic to avoid this situation:
````java
            if (page.getTop() == getAbsY()) {
                pageBreakCount--;
                if (pendingPageName && page == c.getRootLayer().getLastPage()) {
                    c.getRootLayer().removeLastPage();
                    c.setPageName(c.getPendingPageName());
                    c.getRootLayer().addPage(c);
                }
            }
````
Basically, it says that if we are at the top of a page when we encounter a named page, remove the current page and replace it with the named page. Unfortunately, by default, the body has a top margin so we are not at the top of the page when we start the first element. We can fix this with:
````css
body {
  margin-top: 0;
}
````
This removes the empty first page. I think the workaround is simple enough that we can mark this issue as closed. I'll add a reference to this issue from the wiki.

**Comment by Zefling** [comment]
Thanks for this simple solution, we had found a much more complicated workaround.
