### ISSUE TITLE
Spacing ignored when surround by <b> tag

### ISSUE THREAD

**Issue by scoldwell** [danfickle/openhtmltopdf#26]
The following causes the leading spaces to be dropped from the rendered output:

`<b>&#160;&#160;&#160; Text</b><br />`

Whereas the following renders fine:

`&#160;&#160;&#160; <b>Text</b><br />`

**Comment by danfickle** [comment]
I think this was related to #21 as the string width and replacement routines had drifted out of sync, giving an incorrect result. However, it was manifesting for me as too much space in the `<b>` rather than too little so, while it is likely the culprit, I can't be 100% sure that it is the same issue.

@scoldwell - How urgently do you need a release with this fix?

**Comment by scoldwell** [comment]
Would sometime early next week be acceptable? We're still trying to get a release out, but I can instruct the customer how to get around the spacing issue if you need more time than that.

**Comment by danfickle** [comment]
OK, I'll do a release on Sunday or Monday night. I'll close this issue as I'm fairly certain that it's resolved.

**Comment by scoldwell** [comment]
Sounds good. Thanks! Do you have a snapshot repo that I can use to test it out ahead of time?

**Comment by danfickle** [comment]
I've just set this up, so let me know if it works! Add to your pom:

``` xml
 <repositories>
    <repository>
      <id>openhtmltopdf-snapshots</id>
      <name>openhtmltopdf.com snapshots repository</name>
      <url>https://snapshots.openhtmltopdf.com</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

Version is `0.0.1-RC4-SNAPSHOT`

**Comment by scoldwell** [comment]
Getting an error with the snapshot repo:

Connection failed with exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by danfickle** [comment]
It turns out that Java does not yet trust Let's Encrypt https certificates.

There are a few options. 
- Ignore the invalid certificate - see link one (theoretical chance of a man in the middle attack).
- Add the appropriate certificate to your Java implementation - see link two (complicated).
- Wait for Oracle to fix this in an upcoming jdk (rumoured for July).
- Forget snapshots for now and just use official releases.

http://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs
https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/47

**Comment by scoldwell** [comment]
Tested and fixed.  Thanks!
