### ISSUE TITLE
Make output PDF not editable

### ISSUE THREAD

**Issue by conlaoch1** [danfickle/openhtmltopdf#386]
Currently, you can mark text and edit the file in PDF programs. Is there an option to make it "readonly" (i.e. as a pixel graphic)?

Thanks!

**Comment by rototor** [comment]
There is currently no option for that and I don't think that OpenHTMLToPDF should do anything to support that. I don't think that this is something which this project should handle.

To have a PDF without selectable text, I would just use my pdfbox-graphics2d bridge and PDFBox to (re-)render the result PDF which OpenHTMLToPDF creates again on a PDF. With the default settings, all fonts will be converted to vector shapes. So that the text can not be copied. For an example look at this commit:

https://github.com/rototor/pdfbox-graphics2d/commit/038dd76bdf6aba44c42e9ac49b91a21c08b907d5

You will lose all texts (as they are converted to vector shapes) and all images will be recompressed (but you can install a hook to override how the images are compressed). So this will take some time. Also, be aware that the resulting PDF will be *way* bigger than the source PDF because of the vectorized text paths in the PDF. But the PDF is still "resolution independant". 

As an alternative, you can simply use PDFBox to raster images from the PDF pages and embed the images. You can choose to embed the images as JPEG or as a lossless encoded image (which is basically the PNG format). For a sample of how this can be done look at this commit:

https://github.com/rototor/pdfbox-graphics2d/commit/20776b87437f92ab92c1c8cd9166236e0fac6195

I did some quick tests with a small PDF with not many texts. The original PDF had 26 kB, the vectorized PDF had 71 kB, the lossless (=PNG) image PDF had 363 kB and the JPEG image PDF had 756 kB. 

These numbers will vary greatly depending on how much texts and images you have in your PDF. And if you have mainly text in your PDF you will likely stay with the lossless image compression, as it will result in sharp texts and also give the best compression for pure b/w documents.

In the example commit I specified 300 dpi for the image resolution. You can, of course, choose lower dpi values to reduce the image / PDF size. But this will also have a negative impact on readability.

**Comment by danfickle** [comment]
As an extra option you can use a PDF protection policy. However, some viewers will not respect these protections, so if you want greater security, use the suggestion by @rototor. Of course any measure can ultimately be overcome with a photo of the screen and OCR software!

````java
    public static void main(String...args) throws IOException {
        PdfRendererBuilder builder = new PdfRendererBuilder();
        
        builder.withUri("file:///Users/me/Documents/pdf-issues/protected.htm");
        builder.useFastMode();
        try (PdfBoxRenderer renderer = builder.buildPdfRenderer()) {
            renderer.createPDFWithoutClosing();

            try (PDDocument doc = renderer.getPdfDocument()) {
                AccessPermission ap = new AccessPermission();
                ap.setCanModify(false);
                ap.setCanModifyAnnotations(false);
                
                ap.setCanExtractContent(false);
                ap.setCanExtractForAccessibility(true);
                
                ap.setReadOnly();
                
                ProtectionPolicy protection = new StandardProtectionPolicy("owner_password", null, ap);
                doc.protect(protection);
  
                doc.save(new File("/Users/me/Documents/pdf-issues/output/protected.pdf"));
            }
        }
    }
````
