### ISSUE TITLE
Does not support external CSS library.

### ISSUE THREAD

**Issue by DrishtiSoner** [danfickle/openhtmltopdf#388]
**It does not support external css library like bootstrap right!, i need to convert webpage to pdf, can i?**
_I am using this below code_ 
org.w3c.dom.Document doc = html5ParseDocument("https://www.google.com", 3600);
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withW3cDocument(doc, "https://www.google.com/");
            builder.toStream(os);
            builder.run();

_In result it skips most of the properties :_

com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) Invalid at-rule at line 1. Skipping at-rule.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) Found at rule where one of a hex color, ., [, or : was expected at line 1. Skipping ruleset.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) outline is not implemented at line 0. Ignoring declaration.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) -webkit-border-radius is an unrecognized CSS property at line 0. Ignoring declaration.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) -webkit-box-sizing is an unrecognized CSS property at line 0. Ignoring declaration.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) -webkit-animation is an unrecognized CSS property at line 0. Ignoring declaration.
com.openhtmltopdf.css-parse WARNING:: (https://www.google.com/#inline_style_1) Unsupported CSS unit s at line 1. Skipping declaration.

**Comment by danfickle** [comment]
Hi @DrishtiSoner,

This project is built for specifically written HTML templates, rather than rendering arbitrary web pages.

As well as not executing JavaScript, it does not support some of the latest standards such as flexbox and css grid.

Alternatives to look at include puppeteer and selenium.

**Comment by danfickle** [comment]
Assumed solved. Please re-open if required.

**Comment by robert-cronin** [comment]
I'm not sure if there is a deep reason why this library couldn't support CSS3 and flexbox/grid, however I could not find a library better than this one. But I still need it to be in Java and support bootstrap. Is there a simple way it can accommodate this? I don't mind putting in the work.

**Comment by ieugen** [comment]
Hi @robert-cronin , 

Let me see if I can clarify some things. https://github.com/danfickle/openhtmltopdf is not a browser.
It works by reading and parsing the HTML / CSS like a browser does and from these structures it produces a PDF structure. 

It does not take into account all properties of HTML / CSS , just a specific subset. 

Please take into consideration that a fixed PDF page is not fully compatible with a flexible HTML page. 
PDF pages have sizes like A4. Content that does not fit gets to another page.
In a browser content usually flows without page restrictions.

This is why openhtml chose to tranform only specific HTML/CSS syntax to PDF. Most HTML/CSS rules apply of course but some extra restrictions / implementation details are needed because of the differece between HTML and PDF. 
That is why you can load bootstrap into openhtmltopdf and you will get some formatting but not all of it. Since the constructions that work for browsers don't make sense when talking about PDF and how openhtmltopdf team chose to implement the conversion.

**Comment by robert-cronin** [comment]
ok thanks for clearing that up!
