### ISSUE TITLE
How to configure Log Level

### ISSUE THREAD

**Issue by OldManTatze** [danfickle/openhtmltopdf#447]
Hi there,

I am having difficulties with configuring the log level. My goal is to only show ERROR messages.
I know i can disable logging with `XRLog.setLoggingEnabled(false);`. 
However when I try to set the log level for the different loggers with `XRLog.setLevel(XRLog.*Loggername* Level.SEVERE);`, I still get INFO and WARNING -level messages.
Is there any way for me to configure logging to only show ERROR messages?

**Comment by danfickle** [comment]
Our logging is a hot mess. It turns out that we set the default logging levels when the logger is initialized. However, initalization is lazy and only happens on the first log call. So if you can handle one message per JVM, you can use the following:

````java
        XRLog.general(java.util.logging.Level.INFO, "NEW JVM");
        XRLog.listRegisteredLoggers().forEach(logger -> XRLog.setLevel(logger, java.util.logging.Level.SEVERE));
        XRLog.setLevel("com.openhtmltopdf", java.util.logging.Level.SEVERE);
````
You could also write your own logging adapter. XRLogger interface has only three methods that need implementing.

**Comment by OldManTatze** [comment]
Thanks a bunch! With your codesnippet I was able to reduce logging to our desired level. 
This solution is currently acceptable for us. I may however try implementing our own XRLogger in the future. I do not know when and if at all, but if my company allows it, I could post my implementation here for future reference.
