### ISSUE TITLE
Unsupported CSS unit: rem

### ISSUE THREAD

**Issue by leonorader** [danfickle/openhtmltopdf#459]
I love this lib, thanks for creating, it saved my life a few times 😄  ❤️ 
Anyway, we usually use `rem` in our designs and css files so I usually get this:

``` Unsupported CSS unit: rem at line 38. Skipping declaration. ```

Is it possible to add this as a feature? 
I would be new to this library from a developer point of view, but do you think I could develop it and open a PR with this? Or I would really need the help of an experienced contributor?
I would love to help :)

**Comment by danfickle** [comment]
Hi @leonorader,

Thanks for the offer of help. I thought this would be a quick to fix so took it on. It turns out it took a few hours so I should have accepted your offer of a PR!

Anyway, it is fixed now. I would love some help with other issues, even if it is to answer some questions or investigate the cause of the issue.

Thanks again.

**Comment by leonorader** [comment]
@danfickle  Wow! :) Thank you very much! :))

I will try to help, sure! :)
