### ISSUE TITLE
add support "data:image/gif;base64" 

### ISSUE THREAD

**Issue by TomySmit** [danfickle/openhtmltopdf#519]
Add support "data:image/gif;base64" like svg in img tag

**Comment by syjer** [comment]
hi @TomySmit , it's already supported as far as I know.

See https://github.com/danfickle/openhtmltopdf/blob/934340928bb5b51907c36c4c3a86ffc9ccc9c423/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxReplacedElementFactory.java#L89 where it call:

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxUserAgent.java#L75 which load the base 64 encoded image.

**Comment by roman0x58** [comment]
There may be a problem if base64 string has a space before, e.g.

`data:image/png;base64, iVBORw0...` - will not render an image, because constructor of `URI` throws exception here - https://github.com/danfickle/openhtmltopdf/blob/b98f5b801bfc57deed5365f7edebcd359cf6770f/openhtmltopdf-core/src/main/java/com/openhtmltopdf/swing/NaiveUserAgent.java#L410
`data:image/png;base64,iVBORw0...` - will render correctly

**Comment by syjer** [comment]
@roman0x58 interesting, I guess that we need to handle the data uri in a more robust way.

I'll provide a PR to handle this case :D

**Comment by danfickle** [comment]
Fixed with PR provided by @syjer. Re-open as required.
