### ISSUE TITLE
Issue when running on JBoss 

### ISSUE THREAD

**Issue by cloooze** [danfickle/openhtmltopdf#656]
Hi, my code works locally running the war with Spring Boot.
The problem is when I deploy the war on Jboss 7.x.

This is the error I'm getting:
com.openhtmltopdf.exception WARNING:: Couldn't load font (/content/pdf-manager-web.war/WEB-INF/classes/fonts/arial-unicode-ms.ttf). Please check that it is a valid truetype font.

And this is how I load the font:
`builder.useFont(new File(getClass().getClassLoader().getResource("fonts/arial-unicode-ms.ttf").getFile()), "arial");`

Finally, my folder structure:
`/src/main/resources/fonts/arial-unicode-ms.ttf`

Of course fonts folder and file are inside the generated .war under /WEB-INF/classes.

Thank you for your support.

**Comment by syjer** [comment]
hi @cloooze , are you building the war with maven?

If yes, you should ensure the fonts are not "resource-filtered" (basically, it will read and write them as text, so the binary content will be garbled).

See https://github.com/danfickle/openhtmltopdf/issues/360#issuecomment-504648289 .

**Comment by cloooze** [comment]
Hi @syjer , yes I'm building with mavem but I'm not doing any filtering, the font file inside the war is not corrupted (I can open it without any problem).

Thank you for your support btw.

**Comment by danfickle** [comment]
My understanding is that you can not rely on a resource being a conventionally readable file, although it often is during development. Safer to always read it with a stream, possibly to a secure temp file.

**Comment by cloooze** [comment]
Could you share the code to load an InputStream instead of File? thanks

**Comment by syjer** [comment]
`new File(getClass().getClassLoader().getResource("fonts/arial-unicode-ms.ttf").getFile()`

noticed only now, @danfickle is right.

```java

builder.useFont(() -> {
  try {
    return getClass().getClassLoader().getResource("fonts/arial-unicode-ms.ttf").openStream();
  } catch (IOException e) {
    throw new IllegalStateException("was not able to load the font");
  }
}, "arial");
```


Is one way, but I would advise to create a temporary file and copy the font to it at application boot, and then reference this temporary `File`.

**Comment by cloooze** [comment]
It works!
Now I would like to understand what was the problem, I've seen a lot of people using File to load the font.

Would you be so nice to give me a little explenation?

Thanks a lot!!!!!

**Comment by syjer** [comment]
@cloooze , 

btw, you can also do `getResourceAsStream()` so you avoid the `openStream` call.

About why, it should be something along the line of:

using `getFile()` from the getClassloader+getResource call chain will work when you are in a "exploded war" scenario like during the development because you will have the following:

`URL fileUrl = getClass().getClassLoader().getResource("fonts/arial-unicode-ms.ttf")`

In this case, the fileUrl will be: `file:/..../.../fonts/arial-unicode-ms.ttf`.

Calling getFile() will return a path without the protocol -> then doing new File(...) will work, as a file exists in the specified path

But when you are in a deployed war scenario, fileUrl  may be something very similar to:

`classpath:/....../fonts/arial-unicode-ms.ttf` , calling .getFile() -> you will get a path which does not correspondd to a file in the filesystem.

You can check the url type by printing `getClass().getClassLoader().getResource("fonts/arial-unicode-ms.ttf")` .


edit: edited the answer as  I noticed you call getFile() https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#getFile--

**Comment by cloooze** [comment]
Got it, your support is really appreciated. Thank you a lot.

**Comment by danfickle** [comment]
OK, closing now.
