### ISSUE TITLE
table borders: single border display bug with border-collapse: collapse

### ISSUE THREAD

**Issue by gandboy91** [danfickle/openhtmltopdf#752]
When some cell borders are hidden (as 2, 3 and 4 cells in example)
There's buggy behavior of table borders in generated pdf. 
It's usually ok with default 100% zoom level. 
But if it's zoomed in or zoomed out, some borders looks very unstable (cell 3 in example)
Depending on zoom level it can be thinner or thicker than other borders.

example is created with openhtmltopdf sandbox. 
html 

![image](https://user-images.githubusercontent.com/32758032/131338617-aac20d8f-db2d-48cf-94dd-2e87288aea6e.png)

![image](https://user-images.githubusercontent.com/32758032/131338754-c53afa89-cc99-4301-a161-03ab0a11ecfd.png)
![image](https://user-images.githubusercontent.com/32758032/131338968-1e47ab4a-6200-4e61-b8c1-89c49cee3582.png)

markup
```
<table>
  <tr>
    <td>1</td>
    <td class="no-border-right">2</td>
    <td class="no-border-left no-border-right">3</td>
    <td class="no-border-left">4</td>
  </tr>
  <tr>
    <td>5</td>
    <td>6</td>
    <td>7</td>
    <td>8</td>
  </tr>
</table>
```

css 
```
table {
  border-collapse: collapse;
  border: 1px solid black;
}
table td {
  border: 1px solid black;
  width: 100px;
}
table td.no-border-right {
  border-right: none;
}
table td.no-border-left {
  border-left: none;
}
```

P.S. even without border collapse, with cellpadding="0" and some tricks
 like display only right and bottom cell borders and for all table left and top borders
 (to make sure that there's indeed only single border everywhere)
 border thickness is displayed buggy when zoom in/zoom out

**Comment by danfickle** [comment]
I think I've found the culprit!

It turns out to be related to anti-aliasing. Specifically, the top and bottom borders for cell 3 are not anti-aliased while all others are. I think this is because all the other borders need to have a bevel (diagonal edge) (which we calculate explicitly) to meet with vertical lines.

You can see this in effect with the magnifier on your operating system. Alternatively, if using Acrobat, you can turn off anti-aliasing of lines by unticking "Edit Preferences -> Page Display -> Smooth line art". Please reply if changing this setting fixes your actual document so I know I'm going in the right direction. The bad news is that there is no way to turn off AA for lines at the document level. 

The good news is that for most cases we should be able to disable anti-aliasing by not beveling our lines. This should work well for borders where meeting borders are the same color and thickness. With borders meeting different colors or thickness, there doesn't seem to be a great solution.

I'll start work on this.

**Comment by gandboy91** [comment]
Thank you for your fix and explanation! 👍 
Fixing it for one-colored same thickness lines seems enough  for most cases I guess :)

Will wait for next release!
