### ISSUE TITLE
SAXParseException on Attribute href in Tag <a>

### ISSUE THREAD

**Issue by spr333** [danfickle/openhtmltopdf#786]
Hello,

the following html example will produce an exception:
```
<html>
<head>
</head>
<body>
<div>
<a target="_blank"  href="https://www.reichelt.de/tastatur-usb-schwarz-hp-e5e78aa-p304102.html?ACTION=3&GROUPID=6266&ARTICLE=304102&START=0&OFFSET=16&SID=95a14eeeac0e03f0425501092886b5d6a174a5f3f98c09193c5e3&CTYPE=1&MWSTFREE=1" >Link 1</a>
</div>
</body>
</html>
```

Exception:

> SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser
The reference to entity "GROUPID" must end with the ';' delimiter.
Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 112; The reference to entity "GROUPID" must end with the ';' delimiter.

It can be reproduced in the sandbox.

It could be an bug in the parser or it is an configuration issue.

**Comment by danfickle** [comment]
Hi @spr333

Both XHTML inner text and attributes such as `href` must be XHTML escaped. This is a requirement for browser rendered HTML as well (and extremely important to avoid XSS security issues) but the HTML5 parsers used by browsers are much more forgiving of broken input.

XHTML escaping should be done after any url escaping. As a minimum, the ampersand, double quote, less-than and greater-than characters must be escaped. Most template engines will provide escaping functionality or do it by default.

In your case, the problem is the ampersand characters which must be escaped to `&amp;`

P.S. I've been on an open-source mind break so sorry for late reply.

**Comment by spr333** [comment]
Hi @danfickle,

thank you for your answer.
I didn't know that the attributes has to be excaped too in XHTML.
From
`href="https://www.reichelt.de/tastatur-usb-schwarz-hp-e5e78aa-p304102.html?ACTION=3&GROUPID=6266&ARTICLE=304102&START=0&OFFSET=16&SID=95a14eeeac0e03f0425501092886b5d6a174a5f3f98c09193c5e3&CTYPE=1&MWSTFREE=1"`
to
`href="https://www.reichelt.de/tastatur-usb-schwarz-hp-e5e78aa-p304102.html?ACTION=3&amp;GROUPID=6266&amp;ARTICLE=304102&amp;START=0&amp;OFFSET=16&amp;SID=95a14eeeac0e03f0425501092886b5d6a174a5f3f98c09193c5e3&amp;CTYPE=1&amp;MWSTFREE=1"`
and it works.

For the excaping i am using org.apache.commons.text.StringEscapeUtils.escapeXml10(String input).

Thank you for your help.
